#!/usr/bin/env bash

set -e

brew install lua-language-server

go install github.com/nametake/golangci-lint-langserver@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install golang.org/x/tools/gopls@latest

npm install -g \
	graphql-language-service-cli \
	dockerfile-language-server-nodejs
