#!/usr/bin/env zsh

set -e

# Brews
brew install lua-language-server
brew tap incu6us/homebrew-tap
brew install incu6us/homebrew-tap/goimports-reviser
brew install selene

# Go
go install github.com/nametake/golangci-lint-langserver@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest
go install golang.org/x/tools/gopls@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
go install github.com/segmentio/golines@latest
go install github.com/mrtazz/checkmake/cmd/checkmake@latest
go install github.com/mgechev/revive@master
go install golang.org/x/tools/cmd/goimports@latest

# Node
npm install -g \
	pyright \
	graphql-language-service-cli \
	dockerfile-language-server-nodejs \
	@fsouza/prettierd \
	jsonlint \
	eslint_d \
	markdown-toc \
	remark-cli \
	remark-toc \
	remark-preset-lint-consistent \
	remark-preset-lint-recommended \
	markdownlint \
	fixjson

# Ruby
echo -e "Asking for sudo to install ruby gem ffi"
sudo gem pristine ffi --version 1.15.4
gem install mdl --user-install

#Python
pip install mdformat-gfm mdformat-frontmatter mdformat-footnote
