#!/usr/bin/env zsh

set -e

brew install lua-language-server
brew tap incu6us/homebrew-tap
brew install incu6us/homebrew-tap/goimports-reviser

go install github.com/nametake/golangci-lint-langserver@latest
go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
go install github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest
go install golang.org/x/tools/gopls@latest
go install honnef.co/go/tools/cmd/staticcheck@latest
go install github.com/segmentio/golines@latest

npm install -g \
	pyright \
	graphql-language-service-cli \
	dockerfile-language-server-nodejs \
	@fsouza/prettierd \
	jsonlint \
	eslint_d
